///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DatabaseTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DatabaseTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c1c1c840-fb16-4024-8e92-9d798c83d4a3")]
    public partial class DatabaseTestRepository : RepoGenBaseFolder
    {
        static DatabaseTestRepository instance = new DatabaseTestRepository();
        DatabaseTestRepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        DatabaseTestRepositoryFolders.List1000AppFolder _list1000;
        DatabaseTestRepositoryFolders.ExplorerAppFolder _explorer;

        /// <summary>
        /// Gets the singleton class instance representing the DatabaseTestRepository element repository.
        /// </summary>
        [RepositoryFolder("c1c1c840-fb16-4024-8e92-9d798c83d4a3")]
        public static DatabaseTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DatabaseTestRepository() 
            : base("DatabaseTestRepository", "/", null, 0, false, "c1c1c840-fb16-4024-8e92-9d798c83d4a3", ".\\RepositoryImages\\DatabaseTestRepositoryc1c1c840.rximgres")
        {
            _rxmainframe = new DatabaseTestRepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new DatabaseTestRepositoryFolders.List1000AppFolder(this);
            _explorer = new DatabaseTestRepositoryFolders.ExplorerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c1c1c840-fb16-4024-8e92-9d798c83d4a3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("592ef5f6-d718-4620-aaab-c6eb8d1bdd1c")]
        public virtual DatabaseTestRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("cffa53bf-e6f8-4afe-915e-4744376cb6ee")]
        public virtual DatabaseTestRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("78c17e2e-ffaa-40c7-9598-45b533000ec9")]
        public virtual DatabaseTestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DatabaseTestRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("592ef5f6-d718-4620-aaab-c6eb8d1bdd1c")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            DatabaseTestRepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _testdatabase123Info;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _rxbuttonexitInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "592ef5f6-d718-4620-aaab-c6eb8d1bdd1c", "")
            {
                _rxtabstandard = new DatabaseTestRepositoryFolders.RxTabStandardFolder(this);
                _testdatabase123Info = new RepoItemInfo(this, "TestDatabase123", "?/?/tabpage[@accessiblename='Test database']/../tabpage[@accessiblename='Test database']", 30000, null, "e8ea9df6-e965-46a1-8c87-b9861b308f61");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "?/?/tabpage[@controlname='RxTabStandard']/button[@controlname='btnAddPerson']", 30000, null, "ba75290b-876e-4dc4-a341-f4d3b6be3fd0");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", "?/?/tabpage[@controlname='RxTabStandard']/text[@controlname='lblNumberOfPersonsNumber']", 30000, null, "c36540d9-7a8e-4da9-b64a-779986b6fd8d");
                _rxbuttonexitInfo = new RepoItemInfo(this, "RxButtonExit", "button[@controlname='RxButtonExit']", 30000, null, "c0351326-af93-464a-b593-9e8743a0cc64");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("592ef5f6-d718-4620-aaab-c6eb8d1bdd1c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("592ef5f6-d718-4620-aaab-c6eb8d1bdd1c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase123 item.
            /// </summary>
            [RepositoryItem("e8ea9df6-e965-46a1-8c87-b9861b308f61")]
            public virtual Ranorex.TabPage TestDatabase123
            {
                get
                {
                    return _testdatabase123Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase123 item info.
            /// </summary>
            [RepositoryItemInfo("e8ea9df6-e965-46a1-8c87-b9861b308f61")]
            public virtual RepoItemInfo TestDatabase123Info
            {
                get
                {
                    return _testdatabase123Info;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("ba75290b-876e-4dc4-a341-f4d3b6be3fd0")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("ba75290b-876e-4dc4-a341-f4d3b6be3fd0")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("c36540d9-7a8e-4da9-b64a-779986b6fd8d")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("c36540d9-7a8e-4da9-b64a-779986b6fd8d")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The RxButtonExit item.
            /// </summary>
            [RepositoryItem("c0351326-af93-464a-b593-9e8743a0cc64")]
            public virtual Ranorex.Button RxButtonExit
            {
                get
                {
                    return _rxbuttonexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RxButtonExit item info.
            /// </summary>
            [RepositoryItemInfo("c0351326-af93-464a-b593-9e8743a0cc64")]
            public virtual RepoItemInfo RxButtonExitInfo
            {
                get
                {
                    return _rxbuttonexitInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("738356fa-b09d-4119-84cb-ca263b00d350")]
            public virtual DatabaseTestRepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("738356fa-b09d-4119-84cb-ca263b00d350")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "738356fa-b09d-4119-84cb-ca263b00d350", "")
            {
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", 30000, null, "b904b048-623d-49fb-8014-e1669da877d1");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@controlname='rdbMale']", 30000, null, "13f4a664-705e-4799-ae4b-349ebcb80636");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", 30000, null, "889a5d46-221e-4ee4-b542-03843aae9b2c");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", 30000, null, "739bb032-a149-4158-b7d6-8843632ed1f4");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", 30000, null, "50c6edad-ad92-4f4f-861b-69226a03ee91");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("738356fa-b09d-4119-84cb-ca263b00d350")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("738356fa-b09d-4119-84cb-ca263b00d350")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("b904b048-623d-49fb-8014-e1669da877d1")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("b904b048-623d-49fb-8014-e1669da877d1")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("13f4a664-705e-4799-ae4b-349ebcb80636")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("13f4a664-705e-4799-ae4b-349ebcb80636")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("889a5d46-221e-4ee4-b542-03843aae9b2c")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("889a5d46-221e-4ee4-b542-03843aae9b2c")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("739bb032-a149-4158-b7d6-8843632ed1f4")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("739bb032-a149-4158-b7d6-8843632ed1f4")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("50c6edad-ad92-4f4f-861b-69226a03ee91")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("50c6edad-ad92-4f4f-861b-69226a03ee91")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("cffa53bf-e6f8-4afe-915e-4744376cb6ee")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "cffa53bf-e6f8-4afe-915e-4744376cb6ee", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text='Project Management']", 30000, null, "61f82ff0-0460-46c9-9efa-3d722aadced4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cffa53bf-e6f8-4afe-915e-4744376cb6ee")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cffa53bf-e6f8-4afe-915e-4744376cb6ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("61f82ff0-0460-46c9-9efa-3d722aadced4")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("61f82ff0-0460-46c9-9efa-3d722aadced4")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("78c17e2e-ffaa-40c7-9598-45b533000ec9")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@class='Shell_TrayWnd']", parentFolder, 30000, null, true, "78c17e2e-ffaa-40c7-9598-45b533000ec9", "")
            {
                _startInfo = new RepoItemInfo(this, "Start", "?/?/button[@accessiblename='Start']", 30000, null, "ff1f624d-d4d3-46fc-a6f9-ae87e50c9c5b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("78c17e2e-ffaa-40c7-9598-45b533000ec9")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("78c17e2e-ffaa-40c7-9598-45b533000ec9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Start item.
            /// </summary>
            [RepositoryItem("ff1f624d-d4d3-46fc-a6f9-ae87e50c9c5b")]
            public virtual Ranorex.Button Start
            {
                get
                {
                    return _startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Start item info.
            /// </summary>
            [RepositoryItemInfo("ff1f624d-d4d3-46fc-a6f9-ae87e50c9c5b")]
            public virtual RepoItemInfo StartInfo
            {
                get
                {
                    return _startInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
